### ISSUE TITLE
Update GitHub landing page for Sunrise project

### ISSUE THREAD

**Issue by skyriakou** [commercetools/commercetools-sunrise-ios#172]
### What?
Update this page with the most recent content regarding the sunrise projects
https://docs.commercetools.com/sunrise/index.html
https://github.com/commercetools/docs.commercetools.com/blob/master/sunrise/index.html

- Add Test-flight link for downloading the iOS phone and watch app  https://testflight.apple.com/join/pzpGWTe2 
- Replace Sunrise Java entry with Sunrise SPA and add Sunrise SPA demo link 
- Replace image ![Screenshot 2019-09-12 at 15 34 43](https://user-images.githubusercontent.com/44841399/64788587-0c8c7e00-d573-11e9-930e-2891494a0df9.png)
- Replace links https://sunrise.netlify.com/ and https://github.com/commercetools/sunrise-spa
- Remove Sunrise PHP & Sunrise Java links

### Why?
So that users have the latest overview of our sunrise projects 

### Acceptance criteria

- [ ] Users can download the testflight iOS app for phone and watch directly from the above page
- [ ] Users can read about the Sunrise SPA and access Sunrise SPA demo link 
- [ ] Content is reviewed by Laura and Nikola

Let me know if i can help.. Thanks.

**Comment by nikola-mladenovic** [comment]
- Screenshots for the Sunrise iOS app: https://drive.google.com/open?id=1rU0qTUJOh26rqMFJppEes6xD6zUeUQL0 I went ahead and put them in frames, should look better than plain screenshots. @skyriakou - since we need to give Celeste 3 screens per platform, do you have any preference on which 3 to include from the folder I created?

- Link that can be used to install Sunrise app: https://testflight.apple.com/join/pzpGWTe2

- @skyriakou - our new Watch app can be installed using the same link for anyone who has a watch. Do we want to include that as a separate paragraph, or perhaps in the same paragraph where we talk about iOS app? Or perhaps not at all? Depending on your answer, I can also create screenshots for the watch.

**Comment by skyriakou** [comment]
@nikola-mladenovic sure lets include the Watch app as well, so please put in some screenshots. Maybe @celeste-horgan has some ideas of how to best integrate that content :)

**Comment by nikola-mladenovic** [comment]
Added screenshots for the Watch app: https://drive.google.com/open?id=1A6T0zLAL0dduOuf7sEeVqcOz3guIb53G

We also have a couple of different notification scenarios, not sure if that can be interesting for this purpose.

@celeste-horgan if you need more watch app background these two short videos might help:
https://drive.google.com/open?id=1t2niS2bIeHPo4TotuJ359Pu5MRspwQS0
https://drive.google.com/open?id=1c5hkLb_a38Ah6uqqp3Q60QX44pk4AaXq
